### ISSUE TITLE
Capabilities: Handle more bbox elements

### ISSUE THREAD

**Issue by fgravin** [camptocamp/ogc-client#16]
It seems that the bounding boxes of the layers are only fetched from the `BoundingBox` element of the layer in the `getCapabilities`.
eg.
```
<BoundingBox CRS="EPSG:2056" minx="2.1e+06" miny="105000" maxx="2.85e+06" maxy="1.4e+06"/>
```

Additionally, it could exist more elements about the layer extent.

- `EX_GeographicBoundingBox`
- `ows:WGS84BoundingBox`

Those elements are in `EPSG:4326` which simplifies the process afterwards, as it's a standard CRS.

eg.
```xml
<ows:WGS84BoundingBox>
  <ows:LowerCorner>5.140242 45.398181</ows:LowerCorner>
  <ows:UpperCorner>11.47757 48.230651</ows:UpperCorner>
</ows:WGS84BoundingBox>

<EX_GeographicBoundingBox>
  <westBoundLongitude>0.659866</westBoundLongitude>
  <eastBoundLongitude>10.8359</eastBoundLongitude>
  <southBoundLatitude>36.982</southBoundLatitude>
  <northBoundLatitude>48.7511</northBoundLatitude>
</EX_GeographicBoundingBox>

```

**Comment by jahow** [comment]
is that for WMS or WFS?

**Comment by fgravin** [comment]
> is that for WMS or WFS

The exemple above come from [WMS](https://wms.geo.admin.ch/?SERVICE=WMS&REQUEST=GetCapabilities) and [WMTS](https://wmts.geo.admin.ch/EPSG/3857/1.0.0/WMTSCapabilities.xml).
