### ISSUE TITLE
Live Demo and Docs do not open up

### ISSUE THREAD

**Issue by JakobMiksch** [camptocamp/ogc-client#19]
I cannot open the live demo https://camptocamp.github.io/ogc-client/ . I just get a white website.

**Comment by jahow** [comment]
Thanks, indeed the migration to vue3 broke it. Fixed by https://github.com/camptocamp/ogc-client/commit/568606c687887f3577566ea809baae588f4a01df

**Comment by JakobMiksch** [comment]
@jahow no it works. I am closing
