### ISSUE TITLE
dist-node.js missing in dist

### ISSUE THREAD

**Issue by jansule** [camptocamp/ogc-client#50]
In the package.json `main` property, a `dist-node.js` is referenced, which does not seem to exist.

https://github.com/camptocamp/ogc-client/blob/main/package.json#L5
```
  "main": "./dist/dist-node.js",
  "browser": "./dist/index.js",
  "typings": "./dist/index.d.ts",
```

I'm not sure, if this file is missing in the build configs or if `./dist/index.js` should be used instead.

**Comment by jahow** [comment]
Yes I noticed that recently too! we need another entry point for node since some things need to be polyfilled, but for now it's not built.

**Comment by Inlustra** [comment]
@jahow How long do you think until the next release with this fix? 🙏

**Comment by jahow** [comment]
Very soon, there's been a lot of contributions recently so I need to give the library some more testing and then I'll do a release
