### ISSUE TITLE
Support for 'Keywords' in WMS and WFS

### ISSUE THREAD

**Issue by RobQuincey-DC** [camptocamp/ogc-client#54]
Currently, keywords for the service are retrieved from the WMS/WFS capability documents, but keywords added to each `layer` or `featuretype` are not included.

I propose adding a `keywords` property to the layers/featuretypes in the same way it is done at the top level capability document.

**Comment by RobQuincey-DC** [comment]
PR #55 opened with implementation

**Comment by jahow** [comment]
Closed by #55
