### ISSUE TITLE
Add 'abstract' to WMS/WMTS `LayerStyle`

### ISSUE THREAD

**Issue by RobQuincey-DC** [camptocamp/ogc-client#58]
Add the property `abstract` to the `LayerStyle` interface.

Abstract is part of the Style in all versions of WMS and WMTS.

**Comment by RobQuincey-DC** [comment]
Also, apologies for my slightly scatter gun approach to contributing, this library is allowing me to remove huge amounts of hand crafted XML parsing from my code base, so is a life saver, but as I'm going through I'm finding things I want and opening issues. I hope this is OK 😀

**Comment by RobQuincey-DC** [comment]
PR #59 opened

**Comment by jahow** [comment]
> Also, apologies for my slightly scatter gun approach to contributing, this library is allowing me to remove huge amounts of hand crafted XML parsing from my code base, so is a life saver, but as I'm going through I'm finding things I want and opening issues. I hope this is OK 😀

Just saw your comment, it is actually completely fine. Small PRs are much easier to review!
